!
!	GRID251.F90
!	
!
!	Created by allen tang on 12/12/10.
!	Copyright 2012 __MyCompanyName__. All rights reserved.
!
!   CAVITY 251X251
!
PROGRAM MAKE_GRID_WITH_251X251
!
  IMPLICIT NONE
!
  INTEGER, PARAMETER :: INX=255
!
  DOUBLE PRECISION, DIMENSION (INX,INX) :: X,Y
!
!   OUTPUT TYPE : MTYPE = 1
  INTEGER :: MTYPE=1
!
  INTEGER :: MZAHYO=0
!
  INTEGER I,J
  INTEGER :: IMAX=251
  INTEGER :: JMAX=251
  INTEGER :: NCEN=252/2
  INTEGER :: MCEN=252/2
!
  DOUBLE PRECISION CNT
  DOUBLE PRECISION :: AA=0.1 / SQRT(100000.0)
  DOUBLE PRECISION :: BB=1.032052
  DOUBLE PRECISION :: R05=0.5
  DOUBLE PRECISION :: R10=1.0
!
!   GRID GENERATION
  DO I=1,IMAX
    DO J=1,JMAX
	  IF(I.EQ.1) THEN
	    X(I,J)=0.0
	  ELSE IF(I.LT.NCEN) THEN
	    X(I,J)=X(I-1,J)+AA*BB**REAL(I-2)
	  ELSE IF(I.EQ.NCEN) THEN
	    X(I,J)=R05
	  ELSE IF(I.LE.IMAX) THEN
	    X(I,J)=R10-X(NCEN*2-I,J)
	  END IF
	END DO
  END DO
  WRITE(6,*) "X END!"
  DO J=1,JMAX
    DO I=1,IMAX
	  IF(J.EQ.1) THEN
	    Y(I,J)=0.0
	  ELSE IF(J.LT.MCEN) THEN
	    Y(I,J)=Y(I,J-1)+AA*BB**REAL(J-2)
	  ELSE IF(J.EQ.MCEN) THEN
	    Y(I,J)=R05
	  ELSE IF(J.LE.JMAX) THEN
	    Y(I,J)=R10-Y(I,MCEN*2-J)
	  END IF
	END DO
  END DO
  WRITE(6,*) "Y END !"
!
  IF(MTYPE.EQ.0) THEN
    OPEN(UNIT=100,FILE="YOKOJIKU.DAT")
	DO J=1,JMAX
	  DO I=1,IMAX
	    IF(MZAHYO.EQ.1) THEN
		  WRITE(100,*) "(",I,",",J,")=",X(I,J),Y(I,J)
		ELSE
		  WRITE(100,*) X(I,J),Y(I,J)
		END IF
	  END DO
	  WRITE(100,"(1H )")
	END DO
	CLOSE(100)
	OPEN(UNIT=200,FILE="TATEJIKU")
	DO I=1,IMAX
	  DO J=1,JMAX
	    IF(MZAHYO.EQ.1) THEN
		  WRITE(200,*) "(",I,",",J,")=",X(I,J),Y(I,J)
	    ELSE
		  WRITE(200,*) X(I,J),Y(I,J)
		END IF
	  END DO
	  WRITE(200,"(1H )")
	END DO
	CLOSE(200)
	WRITE(6,*) "GRID DATA IS DEFINED."
  ELSE IF(MTYPE.EQ.1) THEN
    OPEN(UNIT=500,FILE="FORT.GR",FORM="UNFORMATTED")
	WRITE(500) IMAX,JMAX
	WRITE(500) ((X(I,J),I=1,IMAX),J=1,JMAX)
	WRITE(500) ((Y(I,J),I=1,IMAX),J=1,JMAX)
	CLOSE(500)
	OPEN(700,FILE="FORT.GD")
	DO I=1,IMAX
	  CNT=0.0
	  WRITE(700," ")
	  DO J=1,JMAX
	    CNT=CNT+1.0
		WRITE(700,"(F18.8,' ',F18.8,' ',F18.8)") CNT,X(I,J),Y(I,J)
	  END DO
	END DO
	CLOSE(700)
	WRITE(6,*) "GRID DATA WAS DONE."
  END IF
!
  STOP 1000
!
END PROGRAM MAKE_GRID_WITH_251X251



